import asyncio
import logging
import time

from pydantic import BaseModel
from pydantic import ValidationError

from linux_mcp_server.config import CONFIG
from linux_mcp_server.gatekeeper.llm import complete_gatekeeper
from linux_mcp_server.utils import StrEnum


logger = logging.getLogger("linux-mcp-server")


def get_model() -> str:
    if CONFIG.gatekeeper.model:
        return CONFIG.gatekeeper.model
    raise ValueError("To use run_script tools, you must set LINUX_MCP_GATEKEEPER__MODEL")


READONLY_INSTRUCTION = """
 * The script does not modify the system in any way, and only does read-only operations.
"""

READONLY_RESULT = """
 * `MODIFIES_SYSTEM`: The script modifies the system in some way.
"""

READONLY_USE_CASES = "get the status of a system, or diagnose a problem"
READWRITE_USE_CASES = "modify system settings, or fix a problem"

PROMPT = """\
The user is using a language model connected to the linux-mcp-server
Model Context Protocol server, and are using it to do one or more of the
following: {use_cases}.

You are a gatekeeper that checks if commands and scripts generated by the
language model are correct and correspond to the user's intent.

# General policies

 * Software can only be installed from repositories that are already
   configured on the system, such as apt or DNF repositories.
   No new repositories may be added.
 * Except for installing software from pre-configured repositories,
   nothing may be downloaded from the internet.

# Your Task

In response to the user's prompt, the language model has generated the
following script of type {script_type}.

<START_OF_SCRIPT>
{script}
<END_OF_SCRIPT>

and has described what the script does with the following text:

<START_OF_DESCRIPTION>
{description}
<END_OF_DESCRIPTION>

Your job is to check that:

{readonly_instruction}* The script does what is described, and does not do anything unrelated.
* It conforms to the general policies outlined above.
* The script is clear and simple and written in an obvious, expected
  manner.
* The script does not contain malicious code or introduce security vulnerabilities
  on the system.

It is *OK* if the script does not consider every possible failure mode, as long
as it fails cleanly. The model may have previously investigated the system
and found out things like the operating system version and configuration
file paths.

The description of the script may reference querying or modifying a specific host;
this is *OK* - the MCP server will take care of executing the script on the
appropriate host. The script does not need to, for example, use SSH to connect to
the target host.

Return a JSON object with the following keys, `status` (required) and `detail` (optional).

status should be one of the following:

* `OK`: The script does what is described and safe to run.
* `BAD_DESCRIPTION`: The script does not do what is described.
* `POLICY`: The script violates one or more of the policies listed under "General Policies" above.
{readonly_result}* `UNCLEAR`: The script is unclear or difficult to understand.
* `DANGEROUS`: The script is likely to cause damage to the system
* `MALICIOUS`: The script contains malicious code or would introduce security vulnerabilities.

If the status is not OK, the detail should be short 1-3 sentence description of
what is wrong with the script. Be specific to allow the language model to correct
the problem.

If the script seems buggy but does not fall into any of the categories above, return
a status of `OK`.

Example response (respond with only the JSON object - do not wrap it in a code block).
{{ "status": "DANGEROUS", "detail": "The critical example file `/etc/example.conf` will be deleted if an error occurs in the first call to sed." }}
"""


# Timeout (s)
GATEKEEPER_TIMEOUT = 120


class GatekeeperStatus(StrEnum):
    OK = "OK"
    BAD_DESCRIPTION = "BAD_DESCRIPTION"
    POLICY = "POLICY"
    MODIFIES_SYSTEM = "MODIFIES_SYSTEM"
    UNCLEAR = "UNCLEAR"
    DANGEROUS = "DANGEROUS"
    MALICIOUS = "MALICIOUS"


class GatekeeperResult(BaseModel):
    status: GatekeeperStatus
    detail: str = ""

    @property
    def description(self) -> str:
        match self.status:
            case GatekeeperStatus.OK:
                return "OK"
            case GatekeeperStatus.BAD_DESCRIPTION:
                return f"Bad description: {self.detail}"
            case GatekeeperStatus.POLICY:
                return f"Policy violation: {self.detail}"
            case GatekeeperStatus.MODIFIES_SYSTEM:
                return f"Script modifies the system and readonly is true: {self.detail}"
            case GatekeeperStatus.UNCLEAR:
                return f"Unclear script: {self.detail}"
            case GatekeeperStatus.DANGEROUS:
                return f"Dangerous script: {self.detail}"
            case GatekeeperStatus.MALICIOUS:
                # We don't provide detail here to make it harder for a malicious model
                # to figure out workarounds
                return "Possibly malicious script: not allowed"
            case _:  # pragma: no cover
                raise ValueError(f"Unknown status: {self.status}")

    @classmethod
    def parse_from_description(cls, description: str) -> "GatekeeperResult":
        """Parse a GatekeeperResult from a description string.

        Args:
            description: A description string like "OK" or "Policy violation: details..."

        Returns:
            A GatekeeperResult with the parsed status and detail

        Raises:
            ValueError: If the description prefix doesn't match any known status
        """
        _prefix_to_status = {
            "OK": GatekeeperStatus.OK,
            "Bad description": GatekeeperStatus.BAD_DESCRIPTION,
            "Policy violation": GatekeeperStatus.POLICY,
            "Script modifies the system and readonly is true": GatekeeperStatus.MODIFIES_SYSTEM,
            "Unclear script": GatekeeperStatus.UNCLEAR,
            "Dangerous script": GatekeeperStatus.DANGEROUS,
            "Possibly malicious script": GatekeeperStatus.MALICIOUS,
        }

        prefix = description.split(":")[0]
        status = _prefix_to_status.get(prefix, None)
        if status is None:
            raise ValueError(f"Unknown description prefix: {description}")

        if status == GatekeeperStatus.OK:
            return cls(status=status, detail="")
        else:
            detail = description[len(prefix) :].lstrip(": ").strip()
            return cls(status=status, detail=detail)


class GatekeeperStats(BaseModel):
    prompt_tokens: int = 0
    completion_tokens: int = 0
    cost: float = 0
    latency: float = 0


class GatekeeperException(Exception):
    def __init__(self, message: str, *, stats: GatekeeperStats | None = None):
        super().__init__(message)
        self.stats = stats


def _compute_cost(prompt_tokens: int, completion_tokens: int, *, usage_cost: float | None = None) -> float:
    if usage_cost is not None:
        return usage_cost
    if CONFIG.gatekeeper.cost is None:
        return 0.0
    input_cost, output_cost = CONFIG.gatekeeper.cost
    return prompt_tokens * input_cost + completion_tokens * output_cost


async def check_run_script_with_stats(
    description: str, script_type: str, script: str, *, readonly: bool
) -> tuple[GatekeeperResult, GatekeeperStats]:
    # Check that the script does what is described
    if "start_of_script" in script.lower() or "end_of_script" in script.lower():
        return GatekeeperResult(
            status=GatekeeperStatus.MALICIOUS, detail="Script contains 'start_of_script' or 'end_of_script'"
        ), GatekeeperStats()

    if "start_of_description" in script.lower() or "end_of_description" in script.lower():
        return GatekeeperResult(
            status=GatekeeperStatus.MALICIOUS, detail="Script contains 'start_of_description' or 'end_of_description'"
        ), GatekeeperStats()

    prompt = PROMPT.format(
        script_type=script_type,
        script=script,
        description=description,
        use_cases=READONLY_USE_CASES if readonly else READWRITE_USE_CASES,
        readonly_instruction=READONLY_INSTRUCTION if readonly else "",
        readonly_result=READONLY_RESULT if readonly else "",
    )

    time_before = time.perf_counter()
    try:
        completion = await asyncio.wait_for(
            asyncio.to_thread(complete_gatekeeper, prompt),
            timeout=GATEKEEPER_TIMEOUT,
        )
    except TimeoutError:
        raise GatekeeperException("Timeout calling gatekeeper model") from None

    stats = GatekeeperStats(
        prompt_tokens=completion.prompt_tokens,
        completion_tokens=completion.completion_tokens,
        cost=_compute_cost(
            completion.prompt_tokens,
            completion.completion_tokens,
            usage_cost=completion.usage_cost,
        ),
        latency=time.perf_counter() - time_before,
    )

    try:
        return GatekeeperResult.model_validate_json(completion.text), stats
    except ValidationError as e:
        logger.warning("Failed to parse gatekeeper model output: %s", e)
        raise GatekeeperException("Failed to parse gatekeeper model output", stats=stats) from e


async def check_run_script(description: str, script_type: str, script: str, *, readonly: bool) -> GatekeeperResult:
    result, _ = await check_run_script_with_stats(description, script_type, script, readonly=readonly)
    return result
